// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/kse-ui/MissionControl.tsx": () => import("../components/mockups/kse-ui/MissionControl.tsx"),
  "./components/mockups/kse-ui/Neural.tsx": () => import("../components/mockups/kse-ui/Neural.tsx"),
  "./components/mockups/kse-ui/Observatory.tsx": () => import("../components/mockups/kse-ui/Observatory.tsx")
};
